-- MySQL Script generated by MySQL Workbench
-- Thu Feb  4 17:55:28 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema decorationManagement
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema decorationManagement
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `decorationManagement` DEFAULT CHARACTER SET utf8 ;
USE `decorationManagement` ;

-- -----------------------------------------------------
-- Table `decorationManagement`.`sys_designer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decorationManagement`.`sys_designer` (
  `id` CHAR(17) NOT NULL COMMENT '@desc 主键id',
  `name` VARCHAR(30) NOT NULL COMMENT '@desc 设计师 名字',
  `description` VARCHAR(255) NOT NULL,
  `createtime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `enable` TINYINT(1) UNSIGNED NOT NULL DEFAULT 1,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decorationManagement`.`sys_materials_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decorationManagement`.`sys_materials_group` (
  `id` CHAR(17) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `group_id` CHAR(17) NOT NULL,
  `designer_id` CHAR(17) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decorationManagement`.`sys_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decorationManagement`.`sys_user` (
  `id` CHAR(17) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `balance` DECIMAL(10,2) NOT NULL DEFAULT 0,
  `enable` TINYINT(1) NOT NULL DEFAULT 1,
  `regtime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decorationManagement`.`sys_scar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decorationManagement`.`sys_scar` (
  `id` CHAR(17) NOT NULL,
  `materials_group_id` CHAR(17) NOT NULL,
  `user_id` CHAR(17) NOT NULL,
  `createtime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `decorationManagement`.`sys_order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `decorationManagement`.`sys_order` (
  `id` CHAR(17) NOT NULL,
  `material_group_id` CHAR(17) NOT NULL,
  `user_id` CHAR(17) NOT NULL,
  `total` DECIMAL(10,2) NOT NULL,
  `status` TINYINT(4) NOT NULL,
  `createtime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
